### ISSUE TITLE
Plexi cannot request TV shows

### ISSUE THREAD

**Issue by collectioncard** [Team-Creative-Name/Plexi#1]
For some reason, totally not because I'm to lazy to get episode requests working, plexi is unable to request television shows. Ideally, Plexi should be able to request the entire show or just the latest season.

Features to add
 - ability to request shows
      - request the latest season
      - request the entire series (disabled via config)

Items to remove
 - remove the hardcoded error response when reacting positively to the show's more info embed.

**Comment by collectioncard** [comment]
Code is mostly in place to enable this
TODO

- [ ] add open to allow full series requests in the config
- [ ] figure out a good name for that...
- [ ] implement that in the settings loader 
- [x] remove hardcoded request block
- [ ] implement new request emotes based upon request type (open to suggestions as to what they should be.
- [ ] fix api calls for these requests

I think that is all for now. I'll add more as I go on.

**Comment by kgranger777** [comment]
This is a problem because it is a problem. Please deproblem this problem so it won't be a problem anymore.

**Comment by collectioncard** [comment]
I've decided on a emoji for the latest season request

--->🆕<---

This emoji will appear next to the thumbs up emoji in a tvSearch embed. Yay! Progress!
